name: skip
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.7=py310h9128911_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.7.2=haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - libffi=3.4.4=hd77b12b_1
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.8=py310h2bbff1b_0
  - mkl_random=1.2.4=py310h59b6b97_0
  - numexpr=2.8.7=py310h2cd9be0_0
  - openssl=1.1.1w=h2bbff1b_0
  - packaging=24.1=py310haa95532_0
  - pandas=2.2.2=py310h5da7b33_0
  - patsy=0.5.6=py310haa95532_0
  - pybind11-abi=5=hd3eb1b0_0
  - python=3.10.0=h96c0403_3
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - statsmodels=0.14.2=py310h827c3e9_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.2=h2eaa2aa_4
  - vs2015_runtime=14.29.30133=h43f2093_4
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
    - absl-py==2.1.0
    - ale-py==0.8.1
    - annotated-types==0.7.0
    - anyio==4.4.0
    - astunparse==1.6.3
    - atari-py==0.2.6
    - atomicwrites==1.4.1
    - attrs==23.2.0
    - autorom==0.4.2
    - autorom-accept-rom-license==0.6.1
    - box2d-py==2.3.5
    - brotli==1.1.0
    - cachetools==5.3.3
    - certifi==2024.7.4
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==1.6.0
    - cmake==3.30.1
    - colorama==0.4.6
    - contourpy==1.2.1
    - cycler==0.12.1
    - cython==3.0.10
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - dopamine==0.7
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.2
    - farama-notifications==0.0.4
    - fasteners==0.19
    - filelock==3.15.4
    - flatbuffers==24.3.25
    - fonttools==4.53.1
    - fsspec==2024.6.1
    - gast==0.4.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - glfw==2.7.0
    - google-auth==2.32.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.64.1
    - gym==0.19.0
    - gym-notices==0.0.8
    - gymnasium==0.29.1
    - h5py==3.11.0
    - identify==2.6.0
    - idna==3.7
    - imageio==2.34.2
    - imageio-ffmpeg==0.5.1
    - importlib-resources==6.4.0
    - iniconfig==2.0.0
    - intel-openmp==2021.4.0
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - keras==2.15.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.5
    - libclang==18.1.1
    - lz4==4.3.3
    - markdown==3.6
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.1
    - mdurl==0.1.2
    - mkl==2021.4.0
    - ml-dtypes==0.2.0
    - more-itertools==10.3.0
    - moviepy==1.0.3
    - mpmath==1.3.0
    - mujoco==2.2.0
    - mujoco-py==2.1.2.14
    - namex==0.0.8
    - networkx==3.3
    - numpy==1.24.3
    - oauthlib==3.2.2
    - opencv-python==4.10.0.84
    - openpyxl==3.1.5
    - opt-einsum==3.3.0
    - optree==0.12.1
    - pillow==10.4.0
    - pip==21.0
    - platformdirs==4.2.2
    - pluggy==1.5.0
    - proglog==0.1.10
    - protobuf==4.25.3
    - psutil==6.0.0
    - pulp==2.9.0
    - py==1.11.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycparser==2.22
    - pydantic==2.8.2
    - pydantic-core==2.20.1
    - pygame==2.1.0
    - pygments==2.18.0
    - pyopengl==3.1.7
    - pyparsing==3.1.2
    - pytest==7.0.1
    - pyyaml==6.0.1
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rich==13.7.1
    - rsa==4.9
    - scikit-learn==1.5.1
    - scipy==1.14.0
    - seaborn==0.13.2
    - sentry-sdk==2.11.0
    - setproctitle==1.3.3
    - setuptools==65.5.0
    - shapely==2.0.5
    - shellingham==1.5.4
    - shimmy==0.2.1
    - smmap==5.0.1
    - sniffio==1.3.1
    - stable-baselines3==2.3.2
    - swig==4.2.1
    - sympy==1.13.0
    - synthesize==0.0.3
    - tbb==2021.13.0
    - tensorboard==2.15.2
    - tensorboard-data-server==0.7.2
    - tensorflow==2.15.0
    - tensorflow-estimator==2.15.0
    - tensorflow-intel==2.15.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - tomli==2.0.1
    - torch==1.13.0
    - torchnet==0.0.4
    - tornado==6.4.1
    - tqdm==4.66.4
    - typer==0.12.3
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - urllib3==2.2.2
    - visdom==0.2.4
    - wandb==0.17.5
    - watchfiles==0.22.0
    - websocket-client==1.8.0
    - werkzeug==3.0.3
    - wheel==0.38.0
    - wrapt==1.14.1
    - xgboost==2.1.0
prefix: E:\anaconda\envs\skip
