wandb_version: 1

grid_x_max:
  desc: null
  value: 29
grid_y_max:
  desc: null
  value: 29
checkpoint:
  desc: null
  value: null
test:
  desc: null
  value: false
actor_lr:
  desc: null
  value: 0.0005
critic_lr:
  desc: null
  value: 0.0005
max_grad_norm:
  desc: null
  value: 2.0
batch_size:
  desc: null
  value: 16
hidden_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.1
num_layers:
  desc: null
  value: 1
train_size:
  desc: null
  value: 32
exist_line_num:
  desc: null
  value: 2
epoch_max:
  desc: null
  value: 4000
initial_station:
  desc: null
  value: 0
first:
  desc: null
  value: null
initial_direct:
  desc: null
  value: null
station_num_lim:
  desc: null
  value: 35
budget:
  desc: null
  value: 270
line_unit_price:
  desc: null
  value: 1.0
station_price:
  desc: null
  value: 5.0
dis_lim:
  desc: null
  value: null
log:
  desc: null
  value: true
method_name:
  desc: null
  value: RLEU
w:
  desc: null
  value:
  - - 0.6
    - 0.2
    - 0.2
social_equity:
  desc: null
  value: 1
factor_weight:
  desc: null
  value: 1
factor_weight1:
  desc: null
  value: 0
result_path:
  desc: null
  value: D:\Study\MORL\Metro-Line/result/
od_index_path:
  desc: null
  value: D:\Study\MORL\Metro-Line/od_index.txt
path_house:
  desc: null
  value: D:\Study\MORL\Metro-Line/index_average_price.txt
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710902517.097304
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
