name: morl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20230802.0=h6a678d5_2
  - absl-py=1.4.0=py310h06a4308_0
  - aiohttp=3.9.0=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py310h06a4308_0
  - attrs=23.1.0=py310h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.6.2=py310h06a4308_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py310h6a678d5_7
  - brotlipy=0.7.0=py310h5764c6d_1004
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2023.11.17=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - cryptography=41.0.7=py310hdda0065_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - fontconfig=2.14.1=h52c9d5c_1
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py310h5eee18b_0
  - geos=3.8.0=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - google-auth=2.22.0=py310h06a4308_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpc-cpp=1.48.2=he1ff14a_4
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtest=1.14.0=hdb19cb5_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.14.0=pyh41d4057_0
  - jedi=0.18.1=py310h06a4308_1
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=py310h06a4308_0
  - jupyter_core=5.5.0=py310h06a4308_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h568e23c_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=15_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=15_linux64_openblas
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=15_linux64_openblas
  - libllvm10=10.0.1=hbcb73fb_5
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py310h06a4308_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - multidict=6.0.4=py310h5eee18b_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy-base=1.26.3=py310hb5e798b_0
  - oauthlib=3.2.2=py310h06a4308_0
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.1=py310h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - platformdirs=3.10.0=py310h06a4308_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pyjwt=2.4.0=py310h06a4308_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=25.1.0=py310h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - shapely=2.0.1=py310h006c72b_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py310h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - traitlets=5.7.1=py310h06a4308_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.9.0=py310h06a4308_0
  - tzdata=2023d=h04d1e81_0
  - urllib3=1.26.18=py310h06a4308_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yarl=1.9.3=py310h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.12.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - about-time==4.2.1
    - alive-progress==3.1.4
    - appdirs==1.4.4
    - asgiref==3.7.2
    - astor==0.8.1
    - autograd==1.6.2
    - black==23.7.0
    - branca==0.6.0
    - chardet==5.2.0
    - charset-normalizer==3.0.1
    - click==8.1.6
    - cloudpickle==1.2.2
    - cma==3.2.2
    - contourpy==1.0.7
    - cplex==22.1.1.0
    - cvxpy==1.3.2
    - deprecated==1.2.14
    - dill==0.3.7
    - django==4.2.2
    - docker-pycreds==0.4.0
    - docplex==2.25.236
    - ecos==2.0.12
    - et-xmlfile==1.1.0
    - ez-setup==0.9
    - farama-notifications==0.0.4
    - filelock==3.13.1
    - fire==0.5.0
    - folium==0.14.0
    - fonttools==4.38.0
    - fsspec==2023.12.2
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.32
    - glfw==2.6.2
    - grapheme==0.6.0
    - grpcio==1.51.1
    - gym==0.15.3
    - gym-notices==0.0.8
    - gym-super-mario-bros==7.4.0
    - gymnasium==0.29.0
    - image==1.5.33
    - imageio==2.31.1
    - jinja2==3.1.2
    - joblib==1.3.1
    - jsonpatch==1.32
    - jsonpointer==2.3
    - markupsafe==2.1.2
    - matplotlib==3.3.2
    - mo-gymnasium==1.0.0
    - mpmath==1.3.0
    - mujoco==2.3.7
    - mypy-extensions==1.0.0
    - nes-py==8.2.1
    - networkx==3.1
    - nose==1.3.7
    - numpy==1.24.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - opencv-contrib-python==4.7.0.68
    - openpyxl==3.1.2
    - osqp==0.6.3
    - pandas==1.5.3
    - pathspec==0.11.2
    - pathtools==0.1.2
    - pillow==9.4.0
    - pip==23.3.1
    - ply==3.11
    - promise==2.3
    - protobuf==3.20.3
    - pulp==2.7.0
    - pyasn1-modules==0.2.8
    - pycddlib==2.1.6
    - pygame==2.5.0
    - pyglet==1.3.2
    - pymoo==0.6.0.1
    - pyomo==6.6.1
    - pyopengl==3.1.7
    - pyqt5-sip==12.11.0
    - pytz==2022.7.1
    - pyutilib==6.0.0
    - pyyaml==6.0.1
    - qdldl==0.1.7.post0
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - scs==3.2.3
    - seaborn==0.12.2
    - sentry-sdk==1.29.2
    - setproctitle==1.3.2
    - setuptools==68.0.0
    - shortuuid==1.0.11
    - sklearn==0.0.post7
    - smmap==5.0.0
    - sqlparse==0.4.4
    - sympy==1.12
    - tensorboardx==2.5.1
    - termcolor==2.3.0
    - threadpoolctl==3.2.0
    - tomli==2.0.1
    - torch==2.1.2
    - torch-tb-profiler==0.4.1
    - torchvision==0.16.2
    - tornado==6.3.1
    - tqdm==4.64.1
    - triton==2.1.0
    - visdom==0.2.4
    - wandb==0.16.1
    - websocket-client==1.5.1
    - werkzeug==2.2.2
    - wrapt==1.15.0
    - xlrd==2.0.1
prefix: /home/liqing/anaconda3/envs/morl
