name: base
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - archspec=0.2.1=pyhd3eb1b0_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - boltons=23.0.0=py311haa95532_0
  - bottleneck=1.3.5=py311h5bb9823_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotli-python=1.0.9=py311hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.12.12=haa95532_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py311h2bbff1b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.1=pyhd8ed1ab_0
  - conda=23.11.0=py311h1ea47a8_1
  - conda-libmamba-solver=23.12.0=pyhd3eb1b0_1
  - conda-package-handling=2.2.0=py311haa95532_0
  - conda-package-streaming=0.9.0=py311haa95532_0
  - contourpy=1.2.0=py311h59b6b97_0
  - cryptography=41.0.7=py311h89fc84f_0
  - cuda-cccl=12.3.101=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.3.101=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.0=py311h12c1d0e_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - distro=1.8.0=py311haa95532_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.13.1=py311haa95532_0
  - fmt=9.1.0=h6d14046_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - future=0.18.3=py311haa95532_0
  - giflib=5.2.1=h8cc25b3_3
  - gmpy2=2.1.2=py311h7f96b67_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.4=py311haa95532_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.0=pyha63f2e9_0
  - ipython=8.20.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=py311haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py311h1ea47a8_0
  - kiwisolver=1.4.4=py311hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libarchive=3.6.2=hb62f4d4_2
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.4.101=0
  - libcurand-dev=10.3.4.101=0
  - libcurl=8.4.0=h86230a5_1
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libiconv=1.16=h2bbff1b_2
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libmamba=1.5.3=hcd6fe79_0
  - libmambapy=1.5.3=py311h77c03ed_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libsodium=1.0.18=h8d14728_1
  - libsolv=0.7.24=h23ce68f_0
  - libssh2=1.10.0=he2ea4bf_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.10.4=h0ad7f3c_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py311h2bbff1b_0
  - matplotlib=3.8.0=py311haa95532_0
  - matplotlib-base=3.8.0=py311hf62ec03_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - menuinst=2.0.1=py311hd77b12b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.8=py311h2bbff1b_0
  - mkl_random=1.2.4=py311h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py311haa95532_0
  - munkres=1.1.4=py_0
  - nest-asyncio=1.5.9=pyhd8ed1ab_0
  - networkx=3.1=py311haa95532_0
  - numexpr=2.8.7=py311h1fcbade_0
  - numpy=1.26.2=py311hdab7c0b_0
  - numpy-base=1.26.2=py311hd01c5d8_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.2.0=hcfcfb64_1
  - packaging=23.1=py311haa95532_0
  - pandas=2.1.4=py311hf62ec03_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.42=h0ff8eda_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py311h045eedc_0
  - pip=23.3.1=py311haa95532_0
  - platformdirs=3.10.0=py311haa95532_0
  - ply=3.11=py311haa95532_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.7=py311ha68e1ae_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py311h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py311haa95532_0
  - pyparsing=3.0.9=py311haa95532_0
  - pyqt=5.15.10=py311hd77b12b_0
  - pyqt5-sip=12.13.0=py311h2bbff1b_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.5=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.1.2=py3.11_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py311haa95532_0
  - pywin32=306=py311h12c1d0e_2
  - pyyaml=6.0.1=py311h2bbff1b_0
  - pyzmq=25.1.2=py311h9250fbb_0
  - qt-main=5.15.2=h19c9488_10
  - reproc=14.2.4=hd77b12b_1
  - reproc-cpp=14.2.4=hd77b12b_1
  - requests=2.31.0=py311haa95532_0
  - ruamel.yaml=0.17.21=py311h2bbff1b_0
  - scipy=1.11.4=py311hc1ccb85_0
  - seaborn=0.12.2=py311haa95532_0
  - setuptools=68.2.2=py311haa95532_0
  - sip=6.7.12=py311hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.3.3=py311h2bbff1b_0
  - tqdm=4.65.0=py311h746a85d_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - truststore=0.8.0=py311haa95532_0
  - typing_extensions=4.7.1=py311haa95532_0
  - tzdata=2023c=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.18=py311haa95532_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - yaml-cpp=0.8.0=hd77b12b_0
  - zeromq=4.3.5=h63175ca_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstandard=0.19.0=py311h2bbff1b_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==2.0.0
      - appdirs==1.4.4
      - cachetools==5.3.2
      - clarabel==0.6.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - cvxpy==1.4.1
      - docker-pycreds==0.4.0
      - ecos==2.0.12
      - et-xmlfile==1.1.0
      - etils==1.6.0
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - glfw==2.6.4
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.0
      - imageio==2.33.1
      - importlib-resources==6.1.1
      - iniconfig==2.0.0
      - markdown==3.5.1
      - mujoco==3.1.1
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - openpyxl==3.1.2
      - osqp==0.6.3
      - pluggy==1.4.0
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pycddlib==2.1.7
      - pyopengl==3.1.7
      - pytest==8.0.0
      - pytest-repeat==0.9.3
      - qdldl==0.1.7.post0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scs==3.2.4.post1
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - shapely==2.0.2
      - smmap==5.0.1
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - torchaudio==2.1.2
      - torchvision==0.16.2
      - wandb==0.16.1
      - werkzeug==3.0.1
prefix: C:\Users\ASUS\.conda\envs\morl
